const express = require("express")
const {createCareers,updatCareersDetails,viewCareers,deleteCareersDetails} = require("../controller/careers_controller")
const router = express.Router()
/**
 * @swagger
 * components:
 *   schemas:
 *     careers:
 *       type: object
 *       required:
 *         - JobId
 *         - JobType
 *         - JobTitle
 *         - RequiredSkill
 *         - ExperienceRequired
 *         - JobDescription
 *         - Responsibilities
 *         - RequiredQualification
 *       properties:
 *         JobId:
 *           type: integer
 *           description: Autogenerated
 *         JobType:
 *           type: string
 *           description: fulltime
 *         JobTitle :
 *           type: string
 *           description: asd
 *         ExperienceRequired:
 *           type: string
 *           description: asd
 *         RequiredQualification:
 *           type: string
 *           description: asd
 *         JobDescription:
 *           type: string
 *           description: asd
 *         Responsibilities:
 *           type: string
 *           description: asd
 *       example:
 *         JobId: Autogenerated
 *         JobType: Fulltime
 *         JobTitle: Fulltime
 *         RequiredSkill: HTML ,CSS
 *         ExperienceRequired: if
 *         JobDescription: ASDF
 *         Responsibilities: poiuy
 *         RequiredQualification: BachelorDegree
 *        
 *
 */

/**
 * @swagger
 * /api/v1/viewCareers:
 *   get:
 *     summary: get all JOB
 *     tags: [careers]
 *     responses:
 *       200:
 *         description: get All careers
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               items:
 *                 $ref: '#/components/schemas/careers'
 */
router.route("/viewCareers").get(viewCareers)


/**
 * @swagger
 * /api/v1/createCareers:
 *   post:
 *     summary:  create a new careers
 *     tags: [careers]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/careers'
 *     responses:
 *       200:
 *         description: careers  create successfull
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/careers'
 *       500:
 *         description: Some server error
 */
 router.route("/createCareers").post(createCareers)

 /**
 * @swagger
 * /api/v1/updatCareersDetails:
 *   post:
 *     summary: update careers Details
 *     tags: [careers]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/careers'
 *     responses:
 *       200:
 *         description: careers update successfull
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/careers'
 *       500:
 *         description: Some server error
 */
  router.route("/updatCareersDetails").post(updatCareersDetails)
/**
 * @swagger
 * /api/v1/deleteCareersDetails/{JobId}:
 *   delete:
 *     summary: Delete an careers
 *     tags: [careers]
 *     parameters:
 *         - in: path
 *           name: JobId
 *           required: true
 *           description: JobId is required
 *           schema:
 *              type: string
 *     responses:
 *       200:
 *         description: careers delete successfully
 *   
 */
 router.route("/deleteCareersDetails/:JobId").delete(deleteCareersDetails)

module.exports = router

