const express = require("express")
const {createDepartment,viewDepartment,updateDepartmentDetails,deleteDepartmentDetails} = require("../controller/department_controller")
const router = express.Router()
/**
 * @swagger
 * components:
 *   schemas:
 *     department:
 *       type: object
 *       required:
 *         - DepartmentId
 *         - DepartMentCode
 *         - DepartmentName
 *       properties:
 *         DepartmentId:
 *           type: integer
 *           description: AutoGenerated
 *         DepartMentCode:
 *           type: string
 *           description: DepartmentCode
 *         DepartmentName:
 *           type: string
 *           description: DepartmentName
 *       example:
 *         DepartmentId: AutoGenerated
 *         DepartMentCode: Depat012
 *         DepartmentName: ANBC
 *        
 *
 */

/**
 * @swagger
 * /api/v1/viewDepartment:
 *   get:
 *     summary: get all department
 *     tags: [department]
 *     responses:
 *       200:
 *         description: get All department
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               items:
 *                 $ref: '#/components/schemas/department'
 */
router.route("/viewDepartment").get(viewDepartment)


/**
 * @swagger
 * /api/v1/createDepartment:
 *   post:
 *     summary: create a new department
 *     tags: [department]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/department'
 *     responses:
 *       200:
 *         description: department create successfull
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/department'
 *       500:
 *         description: Some server error
 */
 router.route("/createDepartment").post(createDepartment)
/**
 * @swagger
 * /api/v1/updateDepartmentDetails:
 *   post:
 *     summary: update department Details
 *     tags: [department]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/department'
 *     responses:
 *       200:
 *         description: department update successfull
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/department'
 *       500:
 *         description: Some server error
 */
 router.route("/updateDepartmentDetails").post(updateDepartmentDetails)
/**
 * @swagger
 * /api/v1/deleteDepartmentDetails/{DepartmentId}:
 *   delete:
 *     summary: Delete an department
 *     tags: [department]
 *     parameters:
 *         - in: path
 *           name: DepartmentId
 *           required: true
 *           description: DepartmentId is required
 *           schema:
 *              type: string
 *     responses:
 *       200:
 *         description: Department delete successfully
 *   
 */
 router.route("/deleteDepartmentDetails/:DepartmentId").delete(deleteDepartmentDetails)

module.exports = router

