const express = require("express")
const {CreateEventDetails,ViewEvent,deleteEventDetails,updateEventDetails} = require("../controller/Event_controller")
const router = express.Router()
/**
 * @swagger
 * components:
 *   schemas:
 *     Event:
 *       type: object
 *       required:
 *         - EventId
 *         - Title
 *         - EventDescription
 *         - EventDate
 *         - EventStartTime
 *         - EventEndTime
 *         - EventPostedBy
 *         - EventLocation
 *         - EventArrangeFor
 *       properties:
 *         EventId:
 *           type: integer
 *           description: EventId
 *         Title:
 *           type: string
 *           description: Title
 *         EventDescription:
 *           type: string
 *           description: Title
 *         EventDate:
 *           type: string
 *           description: Title
 *         EventStartTime:
 *           type: string
 *           description: Title
 *         EventEndTime:
 *           type: string
 *           description: Title
 *         EventPostedBy:
 *           type: string
 *           description: Title
 *         EventLocation:
 *           type: string
 *           description: Title
 *         EventArrangeFor:
 *           type: string
 *           description: Title
 *       example:
 *         EventId: AutoGenerated
 *         Title : ASDF
 *         EventDescription: QWERT
 *         EventDate : 26-09-2022
 *         EventStartTime : 10:00AM
 *         EventEndTime: 7:00PM
 *         EventPostedBy: HR
 *         EventLocation : OfficeHall
 *         EventArrangeFor: Employees
 *        
 *
 */

/**
 * @swagger
 * /api/v1/ViewEvent:
 *   get:
 *     summary: get all Event
 *     tags: [Event]
 *     responses:
 *       200:
 *         description: get All Event
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               items:
 *                 $ref: '#/components/schemas/Event'
 */
router.route("/ViewEvent").get(ViewEvent)
/**
 * @swagger
 * /api/v1/CreateEventDetails:
 *   post:
 *     summary: create a new Event
 *     tags: [Event]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/Event'
 *     responses:
 *       200:
 *         description: create Event successfull
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Event'
 *       500:
 *         description: Some server error
 */
 router.route("/CreateEventDetails").post(CreateEventDetails)
/**
 * @swagger
 * /api/v1/deleteEventDetails/{EventId}:
 *   delete:
 *     summary: Delete an Event
 *     tags: [Event]
 *     parameters:
 *         - in: path
 *           name: EventId
 *           required: true
 *           description: EventId is required
 *           schema:
 *              type: string
 *     responses:
 *       200:
 *         description: Event delete successfully
 *   
 */
 router.route("/deleteEventDetails/:EventId").delete(deleteEventDetails)

 /**
 * @swagger
 * /api/v1/updateEventDetails:
 *   post:
 *     summary: update a  Event
 *     tags: [Event]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/Event'
 *     responses:
 *       200:
 *         description: Event update successfull
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Event'
 *       500:
 *         description: Some server error
 */
router.route("/updateEventDetails").post(updateEventDetails)

module.exports = router

