const express = require("express")
const {CreateHoliday,viewHoliday,deleteHolidayDetails,updateHolidayDetails} = require("../controller/Holiday_controller")
const router = express.Router()
/**
 * @swagger
 * components:
 *   schemas:
 *     holiday:
 *       type: object
 *       required:
 *         - occasionId
 *         - Occasion
 *         - Date
 *         - Day
 *       properties:
 *         occasionId:
 *           type: integer
 *           description: occasionId
 *         Occasion:
 *           type: string
 *           description: Occasion
 *         Date:
 *           type: string
 *           description: Date
 *         Day:
 *           type: string
 *           description: Day
 *       example:
 *         occasionId: autoGenerated
 *         Occasion: Dipawali
 *         Date: 26-10-2022
 *         Day: Saturday
 *        
 *
 */

/**
 * @swagger
 * /api/v1/viewHoliday:
 *   get:
 *     summary: get all holiday
 *     tags: [holiday]
 *     responses:
 *       200:
 *         description: get All holiday
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               items:
 *                 $ref: '#/components/schemas/holiday'
 */
router.route("/viewHoliday").get(viewHoliday)


/**
 * @swagger
 * /api/v1/CreateHoliday:
 *   post:
 *     summary: Create a new Holiday
 *     tags: [holiday]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/holiday'
 *     responses:
 *       200:
 *         description: holiday create successfull
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/holiday'
 *       500:
 *         description: Some server error
 */
 router.route("/CreateHoliday").post(CreateHoliday)
/**
 * @swagger
 * /api/v1/deleteHolidayDetails/{occasionId}:
 *   delete:
 *     summary: Delete an holiday
 *     tags: [holiday]
 *     parameters:
 *         - in: path
 *           name: occasionId
 *           required: true
 *           description: occasionId is required
 *           schema:
 *              type: string
 *     responses:
 *       200:
 *         description: occasion delete successfully
 *   
 */
 router.route("/deleteHolidayDetails/:occasionId").delete(deleteHolidayDetails)

 /**
 * @swagger
 * /api/v1/updateHolidayDetails:
 *   post:
 *     summary: update a  holiday
 *     tags: [holiday]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/holiday'
 *     responses:
 *       200:
 *         description: holiday update successfull
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/holiday'
 *       500:
 *         description: Some server error
 */
router.route("/updateHolidayDetails").post(updateHolidayDetails)

module.exports = router

