const express = require("express")
const {CreateProjectDetails,viewProject,deleteProjectDetails,updateProjectDetails} = require("../controller/Project_controller")
const router = express.Router()
/**
 * @swagger
 * components:
 *   schemas:
 *     Project:
 *       type: object
 *       required:
 *         - ProjectId
 *         - Customer
 *         - ProjectName
 *         - ProjectLink
 *         - Status
 *       properties:
 *         ProjectId:
 *           type: integer
 *           description: ProjectId
 *         ProjectName:
 *           type: integer
 *           description: ProjectName
 *         Customer:
 *           type: integer
 *           description: ProjectId
 *         ProjectLink:
 *           type: integer
 *           description: ProjectId
 *         Status:
 *           type: string
 *           description: Status
 *       example:
 *         ProjectId: autoGenerated
 *         Customer: ASDF
 *         ProjectName: piouy
 *         ProjectLink: http://abcd.com
 *         Status: Active
 *        
 *
 */

/**
 * @swagger
 * /api/v1/viewProject:
 *   get:
 *     summary: get all Project
 *     tags: [Project]
 *     responses:
 *       200:
 *         description: get All Project
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               items:
 *                 $ref: '#/components/schemas/Project'
 */
router.route("/viewProject").get(viewProject)


/**
 * @swagger
 * /api/v1/admin/adminlogin:
 *   post:
 *     summary: add a new project
 *     tags: [Project]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/Project'
 *     responses:
 *       200:
 *         description: create project successfull
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Project'
 *       500:
 *         description: Some server error
 */
 router.route("/CreateProjectDetails").post(CreateProjectDetails)

  /**
 * @swagger
 * /api/v1/deleteProjectDetails/{ProjectId}:
 *   delete:
 *     summary: Delete an Project
 *     tags: [Project]
 *     parameters:
 *         - in: path
 *           name: ProjectId
 *           required: true
 *           description: ProjectId is required
 *           schema:
 *              type: string
 *     responses:
 *       200:
 *         description: Project delete successfully
 *   
 */
router.route("/deleteProjectDetails/:ProjectId").delete(deleteProjectDetails)

/**
* @swagger
* /api/v1/updateProjectDetails:
*   post:
*     summary: update Project Details
*     tags: [Project]
*     requestBody:
*       required: true
*       content:
*         application/json:
*           schema:
*             $ref: '#/components/schemas/Project'
*     responses:
*       200:
*         description: update Project Details successfull
*         content:
*           application/json:
*             schema:
*               $ref: '#/components/schemas/Project'
*       500:
*         description: Some server error
*/
router.route("/updateProjectDetails").post(updateProjectDetails)


module.exports = router

