const express = require("express")
const {createWorkShift,viewWorkShift,deleteWorkShiftDetails,updateWorkShiftDetails} = require("../controller/workShit_controller")
const router = express.Router()
/**
 * @swagger
 * components:
 *   schemas:
 *     workShift:
 *       type: object
 *       required:
 *         - workShiftId
 *         - ShiftId
 *         - EmployeeId
 *         - DepartmentId
 *         - Date
 *       properties:
 *         workShiftId:
 *           type: integer
 *           description: workShiftId
 *         ShiftId:
 *           type: integer
 *           description: ShiftId
 *         EmployeeId:
 *           type: string
 *           description: EmployeeId
 *         DepartmentId:
 *           type: integer
 *           description: DepartmentId
 *         Date:
 *           type: string
 *           description: 09-02-2021
 *       example:
 *         workShiftId: AutoGenerated
 *         ShiftId: 36985
 *         EmployeeId: 1230
 *         DepartmentId: 25801
 *         Date: 24-09-2022
 *        
 *
 */

/**
 * @swagger
 * /api/v1/viewWorkShift:
 *   get:
 *     summary: get all workShift
 *     tags: [workShift]
 *     responses:
 *       200:
 *         description: get All workShift
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               items:
 *                 $ref: '#/components/schemas/workShift'
 */
router.route("/viewWorkShift").get(viewWorkShift)


/**
 * @swagger
 * /api/v1/createWorkShift:
 *   post:
 *     summary: create a new workShift
 *     tags: [workShift]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/workShift'
 *     responses:
 *       200:
 *         description: workShift create successfull
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/workShift'
 *       500:
 *         description: Some server error
 */
 router.route("/createWorkShift").post(createWorkShift)
 /**
 * @swagger
 * /api/v1/deleteWorkShiftDetails/{workShiftId}:
 *   delete:
 *     summary: Delete an workShift
 *     tags: [workShift]
 *     parameters:
 *         - in: path
 *           name: workShiftId
 *           required: true
 *           description: workShiftId is required
 *           schema:
 *              type: string
 *     responses:
 *       200:
 *         description: workShift delete successfully
 *   
 */
router.route("/deleteWorkShiftDetails/:workShiftId").delete(deleteWorkShiftDetails)

/**
* @swagger
* /api/v1/updateWorkShiftDetails:
*   post:
*     summary: update a  WorkShift Details
*     tags: [workShift]
*     requestBody:
*       required: true
*       content:
*         application/json:
*           schema:
*             $ref: '#/components/schemas/workShift'
*     responses:
*       200:
*         description: workShift update successfull
*         content:
*           application/json:
*             schema:
*               $ref: '#/components/schemas/workShift'
*       500:
*         description: Some server error
*/
router.route("/updateWorkShiftDetails").post(updateWorkShiftDetails)


module.exports = router

